TriforceGlowTimer := $412
InitializedWaterfallAnimation := $41F
TitleWaveYs := $420
DemoPhase := $42C
DemoPhase0Subphase1Cycle := $437
DemoItemIds := $444

CharBoardIndex := $41F
InitializedNameField := $420
NameCharOffset := $421
NameInputCharBuf := $422

EndingFlashLongTimer := $4D
PeaceCharDelayCounter := $412
PeaceCharIndex := $413
TextboxCharIndex := $416
TextboxCharPtr := $45F
