ObjWantsToShoot := $412
ObjTurnRate := $41F
ObjTurnTimer := $478

ObjRemDistance := $394

ObjPushTimer := $412

ObjAngleFrac := $380
ObjAngleWhole := $394

Shot_ObjBounceDir := $380
Shot_ObjBounceDist := $394

TileObjRoomId := $412

Fireball_ObjPosFracX := $451
Fireball_ObjPosFracY := $45E
Fireball_ObjDirToTargetX := $412
Fireball_ObjDirToTargetY := $437
Fireball_ObjQSpeedX := $41F
Fireball_ObjQSpeedY := $444

Flyer_ObjSpeedFrac := $412
Flyer_ObjSpeed := $41F
Flyer_ObjTurns := $42C
Flyer_ObjDistTraveled := $437
Flyer_ObjFlyingState := $444
Flyer_ObjOffsetX := $46B
Flyer_ObjOffsetY := $478

Statue_ObjFireballTimer := $4E8

Jumper_ObjSpeedWholeY := $412
Jumper_ObjSpeedFracY := $41F
Jumper_ObjTargetY := $444
Jumper_ObjReversalCount := $451

Wallmaster_ObjStep := $412
Wallmaster_ObjTilesCrossed := $41F

Moldorm_ObjBounceDir := $3BC
Moldorm_ObjOldDir := $380

Digdogger_ObjSpeedFrac := $41F
Digdogger_ObjSpeedWhole := $42C
Digdogger_ObjTargetSpeedFrac := $437
Digdogger_ObjTargetSpeedWhole := $444
Digdogger_ObjSpeedFlag := $45E
Digdogger_ObjIsChild := $46B
Digdogger_ObjCurPart := $478

Aquamentus_ObjFireballOffset := $478

Dodongo_ObjBloatedSubstate := $42C
Dodongo_ObjBombHits := $437
Dodongo_ObjBloatedTimer := $45E

PolsVoice_ObjSpeedWhole := $412
PolsVoice_ObjLastTile := $41F
PolsVoice_ObjTargetY := $42C
PolsVoice_ObjSpeedFrac := $444

Wizzrobe_ObjLastTile := $41F

BlueWizzrobe_ObjTurnCounter := $412

RedWizzrobe_ObjFadeCounter := $394
RedWizzrobe_ObjAnimCounter := $412

Manhandla_ObjSpeedAccum := $412
Manhandla_ObjSpeedFrac := $41F
Manhandla_ObjSpeedWhole := $42C
Manhandla_ObjPrevFrame := $437
Manhandla_ObjFrameAccum := $451
Manhandla_ObjFrame := $478

Manhandla_SegmentJustDied := $383
Manhandla_BounceDir := $385

Gohma_ObjShootTimer := $380
Gohma_ObjDistTraveled := $412
Gohma_ObjMoveAccum := $41F
Gohma_ObjNextOpenEyeCounter := $42C
Gohma_ObjEyeOpenTimer := $444
Gohma_ObjGoStraight := $451
Gohma_ObjSprints := $45E
Gohma_ObjEyeState := $46B
Gohma_ObjEyeAnimCounter := $478

Lamnola_Type := $4E7
Lamnola_Speed := $4E6

Patra_ObjManeuverIndex := $45E

Ganon_ScenePhase := $445

Ganon_ObjAnimationFrame := $46B
Ganon_ObjPhase := $42C
Ganon_ObjCloudDist := $478

Gleeok_NeckXs0 := $438
Gleeok_NeckXs1 := $452
Gleeok_NeckXs2 := $46C
Gleeok_NeckXs3 := $395

Gleeok_NeckYs0 := $445
Gleeok_NeckYs1 := $45F
Gleeok_NeckYs2 := $479
Gleeok_NeckYs3 := $3BD

Gleook_HeadInfo0 := $420
Gleook_HeadInfo1 := $42D
Gleook_HeadInfo2 := $381
Gleook_HeadInfo3 := $3A9

Gleeok_ObjHeadInfo := $413
Gleeok_ObjHeadDirCounterH := $413
Gleeok_ObjHeadDirCounterV := $414
Gleeok_ObjHeadSpeedX := $415
Gleeok_ObjHeadSpeedY := $416
Gleeok_ObjHeadDirChangeCounter := $417
Gleeok_ObjHeadDelay := $418

Gleeok_WrithingCounter := $510

GLEEOK_DIRCOUNTERH = 0
GLEEOK_DIRCOUNTERV = 1
GLEEOK_SPEEDX = 2
GLEEOK_SPEEDY = 3
GLEEOK_DIRCHANGECOUNTER = 4
GLEEOK_DELAY = 5
